# PD01 · Explorar y preparar AGROSAVIA

[Índice y distribución de las cuatro horas](../ejercicios/README.md) · [Guía de pandas](../docs/manual-pandas.md)

**Tiempo de trabajo: 60 minutos.** El objetivo es reconocer la estructura de un DataFrame y preparar medidas y fechas conservando los valores originales.

| Símbolo | Uso |
|:---:|---|
| 📘 | Concepto o función de apoyo. |
| ✅ | Evidencia que debe quedar visible. |
| ⚠️ | Límite de interpretación. |

Esta plantilla se encuentra en `ejercicios/PD01_exploracion_agrosavia.ipynb`. Antes de comenzar, se crea una copia en `soluciones/PD01_exploracion_agrosavia.ipynb` dentro del repositorio de cada estudiante. El desarrollo y la entrega se realizan en esa copia; la plantilla de `ejercicios/` se conserva como enunciado. En JupyterLab se puede duplicar el archivo y mover la copia a `soluciones/`, manteniendo el nombre indicado; si ya existe una solución, se continúa sobre ella. Las instrucciones se presentan en celdas Markdown; las celdas de código marcadas como **Desarrollo** contienen el espacio de trabajo. Cada actividad incluye una celda para explicar el resultado.

Se utiliza el kernel del entorno `.venv` del curso. Los CSV ya deben estar descargados mediante `kit/00_datos.py`. La celda inicial prepara las rutas y carga únicamente las entradas de este ejercicio; el desarrollo del análisis corresponde al estudiante. Este notebook se ejecuta de forma independiente.

**Apoyo en el manual:** secciones 1–5 y la receta de registros en revisión de la sección 11.

## Preparación

Se ejecuta la siguiente celda y se comprueba que el intérprete pertenece al entorno del curso y que pandas corresponde a la versión 2.2.3. Las rutas se calculan desde el repositorio, sin introducir rutas personales de Windows, WSL o macOS.

## Ubicación de trabajo: la raíz del repositorio

📘 **La raíz del repositorio** es la carpeta principal de la copia del proyecto. En la instalación del curso se llama `big-data-postgraduate` y contiene `README.md`, `kit/`, `ejercicios/` y `soluciones/`:

```text
bigdata/
└── big-data-postgraduate/       ← raíz del repositorio
    ├── README.md
    ├── kit/
    ├── ejercicios/              ← enunciados y plantillas
    └── soluciones/              ← notebooks resueltos
```

**Desde la terminal de Ubuntu en WSL.** `pwd` muestra la carpeta actual, `cd` cambia de carpeta y `ls` muestra su contenido. Los siguientes comandos se ejecutan en la terminal, no en una celda Python:

```bash
pwd
cd /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate
pwd
ls
```

✅ Después de `cd`, el segundo `pwd` debe mostrar `/mnt/c/Users/TUPTC/bigdata/big-data-postgraduate`. En la salida de `ls` deben aparecer `README.md`, `kit`, `ejercicios` y `soluciones`. La carpeta `bigdata` es la carpeta contenedora; la raíz del proyecto es su subcarpeta `big-data-postgraduate`.

La ruta anterior corresponde a la configuración de la guía WSL. Si el repositorio se clonó en otra ubicación, se sustituye por la ruta real de esa copia. Si `cd` informa que la carpeta no existe, se revisa esa ubicación antes de continuar.

**Desde una subcarpeta conocida.** `..` significa «carpeta superior». Se comprueba primero la ubicación con `pwd` y se utiliza la alternativa correspondiente:

| Ubicación actual, relativa al repositorio | Comando para volver a la raíz |
|---|---|
| `ejercicios/`, `soluciones/` o `kit/` | `cd ..` |
| `kit/Notebooks/` | `cd ../..` |

Al llegar a la raíz, se puede activar el entorno y abrir JupyterLab desde la terminal:

```bash
source .venv/bin/activate
jupyter lab
```

**Dentro de un notebook ya abierto.** La terminal y el kernel de Python mantienen sus propios directorios de trabajo. La celda de carga siguiente localiza la raíz y la guarda en `REPO`, aunque el notebook esté abierto desde `soluciones/` o `ejercicios/`. Después de ejecutar esa celda, el siguiente bloque puede ejecutarse en una celda Python para comprobar la ubicación y cambiar el directorio del kernel a la raíz:

```python
import os
from pathlib import Path

print("Directorio antes del cambio:", Path.cwd())
print("Raíz detectada:", REPO)
os.chdir(REPO)
print("Directorio después del cambio:", Path.cwd())
```

✅ `Path.cwd()` debe coincidir con `REPO` después del cambio. Esta operación cambia la base para interpretar rutas relativas; el archivo del notebook permanece en `soluciones/`. La carga de datos de estos ejercicios también funciona sin ese cambio porque construye las rutas a partir de `REPO`.

In [1]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import display

actual = Path.cwd().resolve()
REPO = next(
    (ruta for ruta in [actual, *actual.parents]
     if (ruta / "kit/fuentes.json").is_file()
     and (ruta / "kit/00_datos.py").is_file()),
    None,
)
if REPO is None:
    raise FileNotFoundError("El notebook debe abrirse dentro del repositorio del curso")

RAW = REPO / "kit/data/raw"
OUT = REPO / "kit/salidas/soluciones/PD01"
archivos = ['agrosavia.csv']
faltantes = [nombre for nombre in archivos if not (RAW / nombre).is_file()]
if faltantes:
    raise FileNotFoundError(f"Faltan CSV en {RAW}: {faltantes}")
OUT.mkdir(parents=True, exist_ok=True)

opciones = dict(sep=",", encoding="utf-8-sig", dtype=str, keep_default_na=False)
suelo = pd.read_csv(RAW / "agrosavia.csv", **opciones)


print("Python:", sys.version.split()[0])
print("Intérprete:", sys.executable)
print("pandas:", pd.__version__)
print("Repositorio:", REPO)
print("Salidas:", OUT)

Python: 3.12.15
Intérprete: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate/.venv/bin/python
pandas: 2.2.3
Repositorio: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate
Salidas: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate/kit/salidas/soluciones/PD01

## 1. Inspección inicial · 10 minutos

Presentar la cantidad de filas y columnas, los nombres de las columnas, sus tipos y cinco registros. Explicar qué representa una fila y por qué la lectura inicial conserva los campos como texto.

📘 **Apoyo:** `shape`, `columns`, `dtypes`, `head` e `info`.

✅ **Comprobación:** El corte del manifiesto contiene 92.738 filas y 32 columnas. La tabla original debe conservar esa cantidad de filas durante el ejercicio.

In [2]:
# Desarrollo de la actividad 1
# Mostrar dimensiones, tipos y primeros registros de suelo.
# Guardar el total de filas original para los controles posteriores.
total_filas_orig = len(suelo)
print(f"Total de filas originales: {total_filas_orig}")
print(f"Dimensiones (filas, columnas): {suelo.shape}")
print("\nNombres de las columnas:")
print(suelo.columns.tolist())
print("\nTipos de datos iniciales:")
print(suelo.dtypes)
print("\nPrimeros 5 registros:")
display(suelo.head())
suelo.info(memory_usage="deep")
assert total_filas_orig == 92738, f"Se esperaban 92,738 filas pero se obtuvieron {total_filas_orig}"

Total de filas originales: 92738
Dimensiones (filas, columnas): (92738, 32)

Nombres de las columnas:
['Secuencial', 'Fecha de Análisis', 'Departamento', 'Municipio', 'Cultivo', 'Estado', 'Tiempo de establecimiento', 'Topografia', 'Drenaje', 'Riego', 'Fertilizantes aplicados', 'pH agua:suelo', 'Materia organica', 'Fósforo Bray II', 'Azufre Fosfato monocalcico', 'Acidez Intercambiable', 'Aluminio intercambiable', 'Calcio intercambiable', 'Magnesio intercambiable', 'Potasio intercambiable', 'Sodio intercambiable', 'capacidad de intercambio cationico', 'Conductividad electrica', 'Hierro disponible olsen', 'Cobre disponible', 'Manganeso disponible Olsen', 'Zinc disponible Olsen', 'Boro disponible', 'Hierro disponible doble acido', 'Cobre disponible doble acido', 'Manganeso disponible doble acido', 'Zinc disponible doble \xa0acido']

Tipos de datos iniciales:
Secuencial                            object
Fecha de Análisis                     object
Departamento                          object
Municipio                             object
Cultivo                               object
Estado                                object
Tiempo de establecimiento             object
Topografia                            object
Drenaje                               object
Riego                                 object
Fertilizantes aplicados               object
pH agua:suelo                         object
Materia organica                      object
Fósforo Bray II                       object
Azufre Fosfato monocalcico            object
Acidez Intercambiable                 object
Aluminio intercambiable               object
Calcio intercambiable                 object
Magnesio intercambiable               object
Potasio intercambiable                object
Sodio intercambiable                  object
capacidad de intercambio cationico    object
Conductividad electrica               object
Hierro disponible olsen               object
Cobre disponible                      object
Manganeso disponible Olsen            object
Zinc disponible Olsen                 object
Boro disponible                       object
Hierro disponible doble acido         object
Cobre disponible doble acido          object
Manganeso disponible doble acido      object
Zinc disponible doble  acido          object
dtype: object

Primeros 5 registros:

,Secuencial,Fecha de Análisis,Departamento,Municipio,Cultivo,Estado,Tiempo de establecimiento,Topografia,Drenaje,Riego,...,Conductividad electrica,Hierro disponible olsen,Cobre disponible,Manganeso disponible Olsen,Zinc disponible Olsen,Boro disponible,Hierro disponible doble acido,Cobre disponible doble acido,Manganeso disponible doble acido,Zinc disponible doble acido
0,1,7/01/2014,NARIÑO,SAN ANDRÉS DE TUMACO,No Indica,No indica,No indica,No indica,No indica,No indica,...,0.133,66.39,1.700,1.700,1.5,0.187,ND,ND,ND,ND
1,2,21/08/2014,HUILA,SANTA MARÍA,Granadilla,Establecido,De 1 a 5 años,Pendiente,Buen drenaje,No Tiene,...,2.749,250.9,3.7,29.4,28.70,2.084,ND,ND,ND,ND
2,3,22/08/2014,ANTIOQUIA,LIBORINA,Café,Por establecer,No indica,Pendiente,Mal drenaje,No Tiene,...,0.328,390,11.10,8.299,5,0.085,ND,ND,ND,ND
3,4,22/08/2014,ANTIOQUIA,LIBORINA,Maracuyá,Por establecer,No indica,Ondulado,Mal drenaje,No Tiene,...,0.171,200,4.2,4.699,1,0.229,ND,ND,ND,ND
4,5,22/08/2014,ANTIOQUIA,LIBORINA,Café,Por establecer,No indica,Ondulado,Mal drenaje,No Tiene,...,0.323,117.9,3.8,4.600,0.700,0.139,ND,ND,ND,ND

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92738 entries, 0 to 92737
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Secuencial                          92738 non-null  object
 1   Fecha de Análisis                   92738 non-null  object
 2   Departamento                        92738 non-null  object
 3   Municipio                           92738 non-null  object
 4   Cultivo                             92738 non-null  object
 5   Estado                              92738 non-null  object
 6   Tiempo de establecimiento           92738 non-null  object
 7   Topografia                          92738 non-null  object
 8   Drenaje                             92738 non-null  object
 9   Riego                               92738 non-null  object
 10  Fertilizantes aplicados             92738 non-null  object
 11  pH agua:suelo                       92738 non-null  object
 12  Materia organica                    92738 non-null  object
 13  Fósforo Bray II                     92738 non-null  object
 14  Azufre Fosfato monocalcico          92738 non-null  object
 15  Acidez Intercambiable               92738 non-null  object
 16  Aluminio intercambiable             92738 non-null  object
 17  Calcio intercambiable               92738 non-null  object
 18  Magnesio intercambiable             92738 non-null  object
 19  Potasio intercambiable              92738 non-null  object
 20  Sodio intercambiable                92738 non-null  object
 21  capacidad de intercambio cationico  92738 non-null  object
 22  Conductividad electrica             92738 non-null  object
 23  Hierro disponible olsen             92738 non-null  object
 24  Cobre disponible                    92738 non-null  object
 25  Manganeso disponible Olsen          92738 non-null  object
 26  Zinc disponible Olsen               92738 non-null  object
 27  Boro disponible                     92738 non-null  object
 28  Hierro disponible doble acido       92738 non-null  object
 29  Cobre disponible doble acido        92738 non-null  object
 30  Manganeso disponible doble acido    92738 non-null  object
 31  Zinc disponible doble  acido        92738 non-null  object
dtypes: object(32)
memory usage: 157.3 MB

**Interpretación del resultado:**

De lo obtenido se constata que cada fila representa una muestra individual de suelo analizada por AGROSAVIA. Así como que tambien se conservan todas las columnas como texto dtype=str y keep_default_na=False, para evitar que códigos territoriales o identificadores pierdan sus ceros a la izquierda, la coma decimal de valores y para evitar que marcadores de texto como "ND" o campos vacíos se conviertan prematuramente en valores nulos (NaN) sin control previo.

## 2. Diagnóstico de cinco campos · 10 minutos

Construir una tabla llamada `perfil` para `Secuencial`, `Fecha de Análisis`, `Departamento`, `Municipio` y `pH agua:suelo`. Para cada campo se registran los nulos de pandas, los textos vacíos después de retirar espacios y los marcadores `ND`. Las tres situaciones se cuentan por separado.

📘 **Apoyo:** `isna`, `.str.strip`, `.str.upper`, `.eq` y `sum`.

✅ **Comprobación:** `perfil` debe tener una fila por campo. Con `keep_default_na=False`, un texto vacío o `ND` no se convierte automáticamente en un nulo.

In [3]:
# Desarrollo de la actividad 2
# Crear y mostrar perfil con las cinco columnas solicitadas.

campos_interes = ["Secuencial", "Fecha de Análisis", "Departamento", "Municipio", "pH agua:suelo"]

registros_perfil = []
for col in campos_interes:
    s = suelo[col]
    nulos_pandas = s.isna().sum()
    textos_vacios = (s.str.strip() == "").sum()
    marcadores_nd = (s.str.strip().str.upper() == "ND").sum()
    
    registros_perfil.append({
        "campo": col,
        "nulos_pandas": nulos_pandas,
        "textos_vacios": textos_vacios,
        "marcadores_ND": marcadores_nd,
      
    })

perfil = pd.DataFrame(registros_perfil)
display(perfil)

               campo  nulos_pandas  textos_vacios  marcadores_ND
0         Secuencial             0              0              0
1  Fecha de Análisis             0              0              0
2       Departamento             0              0              0
3          Municipio             0              2              0
4      pH agua:suelo             0              0              0

**Interpretación del resultado:**

Se evidencioa que la tabla perfil refleja que, al haber configurado keep_default_na=False en la lectura, la columna nulos_pandas es cero para los cinco campos. En su lugar, los valores faltantes o no registrados se encuentran adecuadamente discriminados entre textos_vacios y marcadores explícitos "ND".

## 3. Conversión de pH y fecha · 15 minutos

Crear `ph` desde `pH agua:suelo` y `fecha_dt` desde `Fecha de Análisis`. Utilizar conversión numérica con `errors="coerce"` y fecha con formato `%d/%m/%Y`. Conservar los originales. Distinguir entradas vacías de textos no vacíos que no pudieron convertirse.

📘 **Apoyo:** `pd.to_numeric`, `.str.replace`, `pd.to_datetime`, `isna` y máscaras booleanas.

✅ **Comprobación:** Se muestran los conteos de conversiones fallidas y hasta cinco ejemplos con su valor original. No se reemplazan medidas ausentes por cero.

In [4]:
# Desarrollo de la actividad 3
# Crear suelo["ph"] y suelo["fecha_dt"].
# Mostrar los fallos de conversión y sus valores originales.

suelo["ph"] = pd.to_numeric(suelo["pH agua:suelo"], errors="coerce")
suelo["fecha_dt"] = pd.to_datetime(suelo["Fecha de Análisis"], format="%d/%m/%Y", errors="coerce")

ph_orig = suelo["pH agua:suelo"].str.strip()
ph_vacio_nd = (ph_orig == "") | (ph_orig.str.upper() == "ND")
ph_fallo_formato = suelo["ph"].isna() & (~ph_vacio_nd)

print(f"pH - Sin formato numérico válido: {suelo['ph'].isna().sum()}")
print(f"  └─ De los cuales son vacíos o ND: {ph_vacio_nd.sum()}")
print(f"  └─ De los cuales son fallos de formato: {ph_fallo_formato.sum()}")

if ph_fallo_formato.sum() > 0:
    print("\nEjemplos de texto con fallo de formato en pH:")
    display(suelo.loc[ph_fallo_formato, ["pH agua:suelo"]].head(5))

fecha_orig = suelo["Fecha de Análisis"].str.strip()
fecha_vacia_nd = (fecha_orig == "") | (fecha_orig.str.upper() == "ND")
fecha_fallo_formato = suelo["fecha_dt"].isna() & (~fecha_vacia_nd)

print(f"\nFecha - Sin fecha válida: {suelo['fecha_dt'].isna().sum()}")
print(f"  └─ De los cuales son vacíos o ND: {fecha_vacia_nd.sum()}")
print(f"  └─ De los cuales son fallos de formato: {fecha_fallo_formato.sum()}")

if fecha_fallo_formato.sum() > 0:
    print("\nEjemplos de texto con fallo de formato en Fecha:")
    display(suelo.loc[fecha_fallo_formato, ["Fecha de Análisis"]].head(5))

pH - Sin formato numérico válido: 11
  └─ De los cuales son vacíos o ND: 0
  └─ De los cuales son fallos de formato: 11

Ejemplos de texto con fallo de formato en pH:

      pH agua:suelo
7282          4..01
46528        >10.00
46530        >10.00
52903         <3.80
56330         <3.80

Fecha - Sin fecha válida: 0
  └─ De los cuales son vacíos o ND: 0
  └─ De los cuales son fallos de formato: 0

**Interpretación del resultado:**
La conversión mediante errors="coerce" permitió transformar los registros válidos a números reales (ph) y objetos de fecha (fecha_dt). Los datos no convertidos corresponden principalmente a ausencias de origen, campos vacíos o "ND", evitando imputar erróneamente un valor cero a registros que realmente carecen de medición.

## 4. Registros para revisión · 15 minutos

Crear la columna booleana `en_revision`. Se marca una fila si su pH es ausente, está fuera de `[0, 14]` o su fecha no se pudo interpretar. Contar por separado cada motivo y el total de filas marcadas. Conservar todas las observaciones.

📘 **Apoyo:** `between`, `isna`, `|`, `~`, `.loc` y `value_counts`.

✅ **Comprobación:** Las filas marcadas y no marcadas deben sumar el total original. Una misma fila puede tener varios motivos; por eso la suma de los motivos no necesariamente coincide con el total marcado.

In [5]:
# Desarrollo de la actividad 4
# Crear en_revision y los conteos por motivo.
# Comprobar la conservación del total original con assert.
motivo_ph_ausente = suelo["ph"].isna()
motivo_ph_fuera_rango = ~suelo["ph"].between(0, 14) & (~motivo_ph_ausente)
motivo_fecha_no_interpretable = suelo["fecha_dt"].isna()

suelo["en_revision"] = motivo_ph_ausente | motivo_ph_fuera_rango | motivo_fecha_no_interpretable

print("Conteos por motivo individual:")
print(f" - pH ausente: {motivo_ph_ausente.sum()}")
print(f" - pH fuera del rango [0, 14]: {motivo_ph_fuera_rango.sum()}")
print(f" - Fecha no interpretable: {motivo_fecha_no_interpretable.sum()}")

print("\nFrecuencia total en revisión:")
print(suelo["en_revision"].value_counts())

total_rev = suelo["en_revision"].sum()
total_ok = (~suelo["en_revision"]).sum()
assert (total_rev + total_ok) == total_filas_orig, "Error: El número total de filas cambió."
print(f"\n✅ Verificación exitosa: Filas en revisión ({total_rev}) + Sin revisión ({total_ok}) = {total_filas_orig} filas originales.")

Conteos por motivo individual:
 - pH ausente: 11
 - pH fuera del rango [0, 14]: 0
 - Fecha no interpretable: 0

Frecuencia total en revisión:
en_revision
False    92727
True        11
Name: count, dtype: int64

✅ Verificación exitosa: Filas en revisión (11) + Sin revisión (92727) = 92738 filas originales.

**Interpretación del resultado:**

Se aprecia que la columna booleana en_revision permite identificar y auditar las filas que contienen inconsistencias sin necesidad de eliminarlas del dataset principal. La suma del total de filas revisadas y no revisadas coincide exactamente con el conteo original de 92.738 registros.

## 5. Evidencias y conclusiones · 10 minutos

Construir `controles` con las columnas `control` y `cantidad`: total de entrada, pH sin número, pH fuera del intervalo, fecha no interpretable y total de filas en revisión. Exportar a `OUT / "controles_agrosavia.csv"` sin índice. Redactar dos hallazgos apoyados en los conteos.

📘 **Apoyo:** `pd.DataFrame`, `to_csv(index=False)` y las tablas de las actividades anteriores.

✅ **Comprobación:** El archivo se genera dentro de la ruta `OUT`. Cada hallazgo menciona un conteo y explica su significado o limitación.

In [6]:
# Desarrollo de la actividad 5
# Construir controles, mostrarlo y exportarlo a OUT.
# Redactar los dos hallazgos en la celda Markdown siguiente.
datos_controles = [
    {"control": "total_entrada", "cantidad": total_filas_orig},
    {"control": "ph_sin_numero", "cantidad": motivo_ph_ausente.sum()},
    {"control": "ph_fuera_intervalo", "cantidad": motivo_ph_fuera_rango.sum()},
    {"control": "fecha_no_interpretable", "cantidad": motivo_fecha_no_interpretable.sum()},
    {"control": "total_filas_en_revision", "cantidad": suelo["en_revision"].sum()}
]

controles = pd.DataFrame(datos_controles)
display(controles)

ruta_salida = OUT / "controles_agrosavia.csv"
controles.to_csv(ruta_salida, index=False, encoding="utf-8-sig")
assert ruta_salida.is_file()
print("Archivo generado:", ruta_salida)

print(f"✅ Archivo exportado exitosamente en: {ruta_salida}")

                   control  cantidad
0            total_entrada     92738
1            ph_sin_numero        11
2       ph_fuera_intervalo         0
3   fecha_no_interpretable         0
4  total_filas_en_revision        11

Archivo generado: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate/kit/salidas/soluciones/PD01/controles_agrosavia.csv
✅ Archivo exportado exitosamente en: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate/kit/salidas/soluciones/PD01/controles_agrosavia.csv

**Interpretación del resultado:**

Hallazgo 1: La mayoría de los registros marcados para revisión se deben a la ausencia del dato de pH (ph_sin_numero), lo que es un porcentaje muy bajo de error, lo que permite que al excluir esas filas practicamente no cambia el tamaño de la muestra.

Hallazgo 2: La cantidad de datos con ph_fuera_intervalo es marginal, lo que muestra que cuando el parámetro numérico de pH existe, generalmente respeta la escala física de 0 a 14.

## Entrega

El notebook completado se conserva como `soluciones/PD01_exploracion_agrosavia.ipynb`. La salida regenerable es `kit/salidas/soluciones/PD01/controles_agrosavia.csv`.

✅ Deben quedar visibles el perfil, los controles de conversión, la conciliación de filas y dos hallazgos. El notebook debe ejecutar todas las celdas en orden después de reiniciar el kernel.

⚠️ El intervalo de pH es un control de dominio para esta práctica. No determina por sí solo una recomendación agronómica. La frecuencia de análisis de suelo no representa automáticamente la distribución de los suelos de todo el territorio.